### ISSUE TITLE
Track way out of alignment, photos upside-down

### ISSUE THREAD

**Issue by talllguy** [Telenav/openstreetview-ios#1]
Finally got around to taking some photos this morning. I went to look at them on the map and noticed that the track is out of alignment, going in the wrong direction completely, and then photos are all upside-down.

In the first screenshot note that after clicking on a photo, the green dot shifts to where it should be. red arrows are my actual route:
![2016-02-25 11_21_12-open street view](https://cloud.githubusercontent.com/assets/1827881/13325965/0c0a655a-dbb2-11e5-8d87-1821c22ac7bf.png)

When I click a photo, some are flipped, others normal:
![2016-02-25 11_22_53-open street view](https://cloud.githubusercontent.com/assets/1827881/13326007/35566652-dbb2-11e5-9fa5-0751f9b8b23c.png)
![2016-02-25 11_23_04-open street view](https://cloud.githubusercontent.com/assets/1827881/13326009/38a80ac2-dbb2-11e5-9180-dea1bc16ffe6.png)

**Comment by talllguy** [comment]
@alexandrui-telenav Tried another one but the upside-down issue still appears to be an issue. In both cases I have the iPhone in a horizontal orientation with the home button on the left (driver's) side.
![2016-02-29 08_37_30-open street view](https://cloud.githubusercontent.com/assets/1827881/13395963/ee3303be-debf-11e5-8045-fa3c40df909f.png)

**Comment by alexandrui-telenav** [comment]
Thanks @talllguy , sorry for the delay.
We fixed the issue with the out of alignment, found to be a polyline encoding issue for certain cases.
The new photos should now also be correctly rotated, but we need to process the previous ones as well.
Work in progress!

**Comment by talllguy** [comment]
@alexandrui-telenav Of course. Will there be a new app deployed, or is this a backend fix?

**Comment by alexandrui-telenav** [comment]
We can fix it on the backend, the photos have rotation info in the EXIF data so that we can rotate properly.

**Comment by talllguy** [comment]
I'll test some more. Sounds good!

**Comment by talllguy** [comment]
No longer occurring, and that line is gone.
