### ISSUE TITLE
Crashes on upload

### ISSUE THREAD

**Issue by talllguy** [Telenav/openstreetview-ios#2]
I shot 2GB worth of street views on my drive this morning. I've been uploading them and the app will occasionally crash to the home screen during this process. Perhaps I can provide crash logs?

**Comment by alexandrui-telenav** [comment]
We have a crash reporting tool and we found the upload crash, thanks for letting us know.
We're sending a new build shortly that tackles that!

**Comment by talllguy** [comment]
No crashes on the newest release
