### ISSUE TITLE
Upload speed decreases as upload time increases

### ISSUE THREAD

**Issue by talllguy** [Telenav/openstreetview-ios#3]
My uploads typically start around 1 MB/s, but steadily fall over the course of the upload. Pausing and Resuming seems to have some positive effect.

![2016-02-29 08 39 38](https://cloud.githubusercontent.com/assets/1827881/13396044/68807c78-dec0-11e5-9106-88ea5ce57601.png)

**Comment by alexandrui-telenav** [comment]
Interesting, we didn't see this behaviour before. Is there another scenario ( in different apps, etc ) where you get constant speed for uploading files?

**Comment by talllguy** [comment]
Seems to have been fixed in a newer release. :+1:
